Add MultipleFilePicker method & MPFile.toByteArray()
Wavesonics/compose-multiplatform-file-picker pull request #86
Opened 2023-11-23 13:47 UTC by Shahriyar13

tested on macOS, iOS, Android

2023-11-23 16:03 UTC, Shahriyar13 commented
Web tested on Safari

2023-11-23 16:50 UTC, Shahriyar13 commented
JVM tested on mac

2023-11-29 14:16 UTC, StefanOltmann commented
Will it work on Windows?

2023-11-29 14:29 UTC, Shahriyar13 commented
> Will it work on Windows?

Yes, but You can choose multiple files only if they are all located in the same folder.

2023-11-29 15:26 UTC, Shahriyar13 commented
@shalva97 @Wavesonics could you check my pull request and accept it please?

2023-11-30 09:11 UTC, shalva97 reviewed
Have not looked at it fully yet. Iam busy these days but I should have some time today and tomorrow

2023-11-30 10:36 UTC, Shahriyar13 commented on .run/iOS Example.run.xml
> +<component name="ProjectRunConfigurationManager">
When You running it in Xcode it's work, also you can skip it by clicking on Debug skip warning.

2023-11-30 10:39 UTC, Shahriyar13 commented on mpfilepicker/src/androidMain/kotlin/com/darkrockstudios/libraries/mpfilepicker/AndroidFilePicker.kt
> +			uri.path?.let {path ->
URI.path is nullable, so if it's happened I will skip it by mapNotNull

2023-12-01 16:46 UTC, shalva97 requested changes

2023-12-01 16:46 UTC, shalva97 commented on examples/macosX64/src/macosX64Main/kotlin/main.kt
> +					multipleFilesPathsChosen = files?.map { it.path + "/n" } ?: listOf()
should be \ instead
```suggestion
					multipleFilesPathsChosen = files?.map { it.path + "\n" } ?: listOf()
```

2023-12-01 16:46 UTC, shalva97 commented on examples/jvm/src/main/kotlin/Main.kt
> +		pathMultiChosen = files?.map { it.path + "/n" } ?: emptyList()
```suggestion
		pathMultiChosen = files?.map { it.path + "\n" } ?: emptyList()
```

2023-12-01 16:46 UTC, shalva97 commented on examples/ios/src/iosMain/kotlin/main.ios.kt
> +						.map { it.path + "/n" }
```suggestion
						.map { it.path + "\n" }
```

2023-12-01 16:51 UTC, shalva97 commented
It's great. Tested it on MacOS and works perfectly.

Was there a specific reason that you have added a new function `MultipleFilePicker` instead of adding a new argument to an old `FilePicker` function? At least this is how I would do it...

Don't pay attention to CI/CD. I have canceled it because for some reason build takes too much time.

Accept few code suggestions and I will merge it.

2023-12-04 14:44 UTC, shalva97 commented
yes, that makes sense.

@Wavesonics Should I merge this directly? for me it looks good

2023-12-05 15:47 UTC, merged